name: Deploy to AKS using Helm Chart
  
on:  
  push:  
    branches:  
      - main  
  
env:  
  REGISTRY_PACKAGE: ghcr.io/keshari0840/helloworld:20240626-195250734 # Enter the name of the GitHub Package Registry package  
  HELM_CHART: java-chart # Enter the name of the Helm chart  
  AKS_CLUSTER: PcfToAksMigration # Enter the name of your AKS cluster  
  AKS_NAMESPACE: <aks_namespace> # Enter the namespace where you want to deploy the image
  AKS_RESOURCE_GROUP: rg_fedex_east_us # Enter the name of your AKS resource group
  
jobs:  
  deploy:  
    permissions:
        actions: read
        contents: read
        id-token: write
    runs-on: ubuntu-latest  
  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  
  
      - name: Set up Helm  
        uses: azure/setup-helm@v1  

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show 
  
      - name: Fetch image from GitHub Package  
        run: |  
          echo ${{ secrets.TOKEN_GITHUB }} | gh auth login --with-token  
          gh package download -y ghcr.io/${{ github.repository_owner }}/${{ env.REGISTRY_PACKAGE }}@${{ github.sha }} -R  
  
      - name: Deploy to AKS using Helm  
        run: |  
          az aks get-credentials --name ${{ env.AKS_CLUSTER }} --resource-group ${{ env.AKS_RESOURCE_GROUP }}  
          helm upgrade --install ${{ env.HELM_CHART }} ./java-chart \  
            --namespace ${{ env.AKS_NAMESPACE }} \  
            --set image.repository=${REGISTRY_PACKAGE} \  
            --set image.tag=${{ github.sha }}  
